name: Build and Deploy Pelican Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install Pelican and dependencies
      run: |
        pip install pelican Markdown && pip install pelican-youtube

    - name: Build Pelican website
      run: |
        pelican content -o output -s pelicanconf.py
      env:
        PELICAN_CONTENT: content

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        publish_branch: gh-pages
